In [31]:
import numpy as np
import matplotlib.pyplot as plt
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
x = np.linalg.solve(A, B)
print ("Матрица A:\n", A)
print ("Вектор B:\n",B)
print ("Решение системы:\n", x)

Матрица A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Вектор B:
 [12  2  1]
Решение системы:
 [-4.05323966e+16  8.10647933e+16 -4.05323966e+16]


In [32]:
r1 = np.linalg.matrix_rank(A)
r2 = np.linalg.matrix_rank(B)
print ("Ранг матрицы A:", r1)
print ("Ранг матрицы B:", r2)

Ранг матрицы A: 2
Ранг матрицы B: 1


In [36]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])
r1 = np.linalg.matrix_rank(A)
r = np.linalg.matrix_rank(b)
print ("Матрица A:\n", A)
print ("Ранг матрицы A:", r)
print ("Измененный вектор B:\n",b)
print ("Ранг измененной матрицы B:", r)

Матрица A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы A: 1
Измененный вектор B:
 [1 1 1]
Ранг измененной матрицы B: 1


In [37]:

x = np.linalg.solve(A, b)
print ("Матрица A:\n", A)
print ("Измененный вектор B:\n",b)
print ("Решение системы:\n", x)

Матрица A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Измененный вектор B:
 [1 1 1]
Решение системы:
 [-2.5  4.  -1.5]
