In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([2, 5, 1])
x, res, r, s = np.linalg.lstsq(a, b, rcond=None)
print ("Матрица A:\n", a)
print ("Вектор b:\n", b)
print ("Псевдорешение системы:\n", x)

Матрица A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Вектор b:
 [2 5 1]
Псевдорешение системы:
 [-1.80555556 -0.05555556  1.69444444]
