In [4]:
import numpy as np
import matplotlib.pyplot as plt
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
x = np.linalg.solve(A, B)
print ("Матрица A:\n", A)
print ("Вектор B:\n",B)
print ("Решение системы:\n", x)

Матрица A:
 [[1 2 3]
 [4 0 6]
 [7 8 9]]
Вектор B:
 [12  2  1]
Решение системы:
 [-9.2         0.9         6.46666667]


In [8]:
print ("Проверка:", A.dot(x))

Проверка: [12.  2.  1.]
