In [29]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print ("Матрица P:\n", P)
print ("Матрица L:\n", L)
print ("Матрица U:\n", U)

Матрица P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Матрица L:
 [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
Матрица U:
 [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [30]:
print(np.dot(P, A) - np.dot(L, U))

[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]
