In [3]:
import numpy as np
import matplotlib.pyplot as plt
A = np.array([[1, 2, 1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

C:\Users\kushn\AppData\Local\Temp/ipykernel_9296/4286396035.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.22624108, -0.71604718, -0.69545345]),
 array([5.21202515]),
 3,
 array([15.2235428 ,  9.45710672,  4.21981957]))

In [4]:
np.dot(A, [1.22624108, -0.71604718, -0.69545345])

array([-0.90130673,  6.54291196, 11.99925764,  5.92974941, 15.49263731])

In [5]:
def Q(x, y, z):
    return((np.linalg.norm(np.dot(A, [x, y, z]) -B))**2)
Q(1.22624108, -0.71604718, -0.69545345)

5.21202515355209